name: shared_preferences_example
description: Testbed for the shared_preferences_foundation implementation.
publish_to: none

environment:
<<<<<<< HEAD
<<<<<<< HEAD
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"
=======
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"
>>>>>>> refs/remotes/origin/main
=======
  sdk: ^3.2.3
  flutter: ">=3.16.6"
>>>>>>> refs/remotes/origin/main

dependencies:
  flutter:
    sdk: flutter
  shared_preferences_foundation:
    # When depending on this package from a real application you should use:
    #   shared_preferences_foundation: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  shared_preferences_platform_interface:
    git: https://github.com/kumsumit/shared_preferences_platform_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
