name: shared_preferences_foundation
publish_to: none
description: iOS and macOS implementation of the shared_preferences plugin.
repository: https://github.com/flutter/packages/tree/main/packages/shared_preferences/shared_preferences_foundation
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+shared_preferences%22
version: 2.3.4

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    implements: shared_preferences
    platforms:
      ios:
        pluginClass: SharedPreferencesPlugin
        dartPluginClass: SharedPreferencesFoundation
        sharedDarwinSource: true
      macos:
        pluginClass: SharedPreferencesPlugin
        dartPluginClass: SharedPreferencesFoundation
        sharedDarwinSource: true

dependencies:
  flutter:
    sdk: flutter
  shared_preferences_platform_interface:
    git: https://github.com/kumsumit/shared_preferences_platform_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: 
    git: https://github.com/kumsumit/pigeon.git

topics:
  - persistence
  - shared-preferences
  - storage
